"""change_user_id_to_uuid

Revision ID: dcd54eb73dfd
Revises: aecc71050380
Create Date: 2026-04-01 14:59:39.932082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dcd54eb73dfd'
down_revision: Union[str, Sequence[str], None] = 'aecc71050380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('TRUNCATE TABLE subscriptions')
    op.execute('ALTER TABLE subscriptions ALTER COLUMN user_id TYPE UUID USING user_id::uuid')
    op.alter_column('subscriptions', 'user_id',
                    existing_type=sa.String(),
                    type_=sa.dialects.postgresql.UUID(as_uuid=True),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_event', 'subscriptions', type_='unique')
    op.execute('ALTER TABLE subscriptions ALTER COLUMN user_id TYPE VARCHAR USING user_id::varchar')
    op.create_unique_constraint('subscriptions_user_id_event_id_key', 'subscriptions', ['user_id', 'event_id'])
    # ### end Alembic commands ###
